import type {
  DietaryTag,
  GroceryItem,
  Meal,
  Store,
  StoreProduct,
} from "@/types";

export const startingGroceryItems: GroceryItem[] = [
];

export const stores: Store[] = [
  {
    id: "coles",
    name: "Coles",
    distanceKm: null,
    latitude: -33.8796,
    longitude: 151.2053,
  },
  {
    id: "woolworths",
    name: "Woolworths",
    distanceKm: null,
    latitude: -33.8659,
    longitude: 151.2073,
  },
];

export const storePricing: Record<string, StoreProduct[]> = {
  coles: [
    {
      listItemName: "eggs",
      displayName: "Coles Free Range Eggs x12",
      packageSize: 12,
      packageUnit: "x",
      packagePrice: 6.5,
      packsNeeded: 0,
      lineTotal: 0,
      imageUrl: null,
      available: true,
    },
    {
      listItemName: "butter",
      displayName: "Coles Unsalted Butter 250g",
      packageSize: 250,
      packageUnit: "g",
      packagePrice: 4.8,
      packsNeeded: 0,
      lineTotal: 0,
      imageUrl: null,
      available: true,
    },
    {
      listItemName: "milk",
      displayName: "Coles Full Cream Milk 2L",
      packageSize: 2,
      packageUnit: "L",
      packagePrice: 3.1,
      packsNeeded: 0,
      lineTotal: 0,
      imageUrl: null,
      available: true,
    },
    {
      listItemName: "sugar",
      displayName: "Coles White Sugar 1kg",
      packageSize: 1,
      packageUnit: "kg",
      packagePrice: 2.2,
      packsNeeded: 0,
      lineTotal: 0,
      imageUrl: null,
      available: true,
    },
    {
      listItemName: "rice",
      displayName: "Coles Long Grain Rice 1kg",
      packageSize: 1,
      packageUnit: "kg",
      packagePrice: 3,
      packsNeeded: 0,
      lineTotal: 0,
      imageUrl: null,
      available: true,
    },
    {
      listItemName: "cheese",
      displayName: "Coles Tasty Cheese 500g",
      packageSize: 500,
      packageUnit: "g",
      packagePrice: 6.5,
      packsNeeded: 0,
      lineTotal: 0,
      imageUrl: null,
      available: true,
    },
    {
      listItemName: "flour",
      displayName: "Coles Plain Flour 1kg",
      packageSize: 1,
      packageUnit: "kg",
      packagePrice: 2,
      packsNeeded: 0,
      lineTotal: 0,
      imageUrl: null,
      available: true,
    },
    {
      listItemName: "chicken",
      displayName: "Coles RSPCA Approved Chicken Breast 1kg",
      packageSize: 1,
      packageUnit: "kg",
      packagePrice: 11,
      packsNeeded: 0,
      lineTotal: 0,
      imageUrl: null,
      available: true,
    },
    {
      listItemName: "bread",
      displayName: "Coles White Sandwich Bread",
      packageSize: 1,
      packageUnit: "x",
      packagePrice: 3.5,
      packsNeeded: 0,
      lineTotal: 0,
      imageUrl: null,
      available: true,
    },
    {
      listItemName: "pasta",
      displayName: "Coles Penne Pasta 500g",
      packageSize: 500,
      packageUnit: "g",
      packagePrice: 2,
      packsNeeded: 0,
      lineTotal: 0,
      imageUrl: null,
      available: true,
    },
  ],
  woolworths: [
    {
      listItemName: "eggs",
      displayName: "Woolworths Free Range Eggs x12",
      packageSize: 12,
      packageUnit: "x",
      packagePrice: 7,
      packsNeeded: 0,
      lineTotal: 0,
      imageUrl: null,
      available: true,
    },
    {
      listItemName: "butter",
      displayName: "Woolworths Unsalted Butter 500g",
      packageSize: 500,
      packageUnit: "g",
      packagePrice: 7,
      packsNeeded: 0,
      lineTotal: 0,
      imageUrl: null,
      available: true,
    },
    {
      listItemName: "milk",
      displayName: "Woolworths Full Cream Milk 2L",
      packageSize: 2,
      packageUnit: "L",
      packagePrice: 3.3,
      packsNeeded: 0,
      lineTotal: 0,
      imageUrl: null,
      available: true,
    },
    {
      listItemName: "sugar",
      displayName: "Woolworths White Sugar 1kg",
      packageSize: 1,
      packageUnit: "kg",
      packagePrice: 2.4,
      packsNeeded: 0,
      lineTotal: 0,
      imageUrl: null,
      available: true,
    },
    {
      listItemName: "rice",
      displayName: "Woolworths Long Grain Rice 1kg",
      packageSize: 1,
      packageUnit: "kg",
      packagePrice: 3.2,
      packsNeeded: 0,
      lineTotal: 0,
      imageUrl: null,
      available: true,
    },
    {
      listItemName: "cheese",
      displayName: "Woolworths Tasty Cheese 500g",
      packageSize: 500,
      packageUnit: "g",
      packagePrice: 7.2,
      packsNeeded: 0,
      lineTotal: 0,
      imageUrl: null,
      available: true,
    },
    {
      listItemName: "flour",
      displayName: "Woolworths Plain Flour 1kg",
      packageSize: 1,
      packageUnit: "kg",
      packagePrice: 2.2,
      packsNeeded: 0,
      lineTotal: 0,
      imageUrl: null,
      available: true,
    },
    {
      listItemName: "chicken",
      displayName: "Woolworths Chicken Breast Fillets 1kg",
      packageSize: 1,
      packageUnit: "kg",
      packagePrice: 12.5,
      packsNeeded: 0,
      lineTotal: 0,
      imageUrl: null,
      available: true,
    },
    {
      listItemName: "bread",
      displayName: "Woolworths Soft White Sandwich Bread",
      packageSize: 1,
      packageUnit: "x",
      packagePrice: 3.8,
      packsNeeded: 0,
      lineTotal: 0,
      imageUrl: null,
      available: true,
    },
    {
      listItemName: "pasta",
      displayName: "Woolworths Penne Pasta 500g",
      packageSize: 500,
      packageUnit: "g",
      packagePrice: 2.3,
      packsNeeded: 0,
      lineTotal: 0,
      imageUrl: null,
      available: true,
    },
  ],
};

export const mealPrepMeals: Meal[] = [
  {
    id: "japanese-fluffy-cheesecake",
    name: "Japanese Fluffy Cheesecake",
    description: "A light and fluffy cake for all your baking desires",
    attribution: "Recipe from: Wow Ricky is so good at baking",
    imageUrl: null,
    ingredients: [
      { name: "eggs", quantity: 4, unit: "x" },
      { name: "butter", quantity: 50, unit: "g" },
      { name: "milk", quantity: 100, unit: "ml" },
      { name: "sugar", quantity: 100, unit: "g" },
      { name: "flour", quantity: 80, unit: "g" },
    ],
    dietaryTags: ["vegetarian", "halal"],
    isQuickMeal: false,
    isHighProtein: false,
  },
  {
    id: "spaghetti-bolognese",
    name: "Spaghetti Bolognese",
    description: "A rich tomato and beef pasta made for an easy dinner",
    attribution: "Recipe from: The LetHim Cook kitchen",
    imageUrl: null,
    ingredients: [
      { name: "pasta", quantity: 500, unit: "g" },
      { name: "beef", quantity: 500, unit: "g" },
      { name: "cheese", quantity: 100, unit: "g" },
    ],
    dietaryTags: [],
    isQuickMeal: false,
    isHighProtein: true,
  },
  {
    id: "vegetable-curry",
    name: "Vegetable Curry",
    description: "A warm and comforting curry packed with colourful vegetables",
    attribution: "Recipe from: The LetHim Cook kitchen",
    imageUrl: null,
    ingredients: [
      { name: "rice", quantity: 300, unit: "g" },
      { name: "vegetables", quantity: 500, unit: "g" },
      { name: "coconut milk", quantity: 400, unit: "ml" },
    ],
    dietaryTags: ["vegan", "vegetarian", "halal", "nut-allergy"],
    isQuickMeal: false,
    isHighProtein: false,
  },
  {
    id: "chicken-teriyaki",
    name: "Chicken Teriyaki",
    description: "Sweet and savoury glazed chicken served with steamed rice",
    attribution: "Recipe from: The LetHim Cook kitchen",
    imageUrl: null,
    ingredients: [
      { name: "chicken", quantity: 500, unit: "g" },
      { name: "rice", quantity: 300, unit: "g" },
      { name: "sugar", quantity: 30, unit: "g" },
    ],
    dietaryTags: ["halal"],
    isQuickMeal: false,
    isHighProtein: true,
  },
];

export const mealSuggestionCatalogue: Meal[] = [
  {
    id: "cheesy-egg-fried-rice",
    name: "Cheesy Egg Fried Rice",
    description: "",
    attribution: "",
    imageUrl: null,
    ingredients: [
      { name: "eggs", quantity: null, unit: "" },
      { name: "rice", quantity: null, unit: "" },
      { name: "cheese", quantity: null, unit: "" },
      { name: "butter", quantity: null, unit: "" },
    ],
    dietaryTags: ["vegetarian", "halal"],
    isQuickMeal: true,
    isHighProtein: true,
  },
  {
    id: "creamy-cheese-omelette",
    name: "Creamy Cheese Omelette",
    description: "",
    attribution: "",
    imageUrl: null,
    ingredients: [
      { name: "eggs", quantity: null, unit: "" },
      { name: "milk", quantity: null, unit: "" },
      { name: "cheese", quantity: null, unit: "" },
      { name: "butter", quantity: null, unit: "" },
    ],
    dietaryTags: ["vegetarian", "halal"],
    isQuickMeal: true,
    isHighProtein: true,
  },
  {
    id: "buttery-rice-bowl",
    name: "Buttery Rice Bowl",
    description: "",
    attribution: "",
    imageUrl: null,
    ingredients: [
      { name: "rice", quantity: null, unit: "" },
      { name: "butter", quantity: null, unit: "" },
    ],
    dietaryTags: ["vegetarian", "halal"],
    isQuickMeal: true,
    isHighProtein: false,
  },
  {
    id: "homestyle-rice-pudding",
    name: "Homestyle Rice Pudding",
    description: "",
    attribution: "",
    imageUrl: null,
    ingredients: [
      { name: "rice", quantity: null, unit: "" },
      { name: "milk", quantity: null, unit: "" },
      { name: "sugar", quantity: null, unit: "" },
    ],
    dietaryTags: ["vegetarian", "halal"],
    isQuickMeal: false,
    isHighProtein: false,
  },
  {
    id: "protein-pancakes",
    name: "Protein Pancakes",
    description: "",
    attribution: "",
    imageUrl: null,
    ingredients: [
      { name: "eggs", quantity: null, unit: "" },
      { name: "milk", quantity: null, unit: "" },
      { name: "oats", quantity: null, unit: "" },
    ],
    dietaryTags: ["vegetarian", "halal"],
    isQuickMeal: true,
    isHighProtein: true,
  },
  {
    id: "slow-roasted-tomato-pasta",
    name: "Slow Roasted Tomato Pasta",
    description: "",
    attribution: "",
    imageUrl: null,
    ingredients: [
      { name: "tomato", quantity: null, unit: "" },
      { name: "pasta", quantity: null, unit: "" },
      { name: "garlic", quantity: null, unit: "" },
    ],
    dietaryTags: ["vegan", "vegetarian", "halal"],
    isQuickMeal: false,
    isHighProtein: false,
  },
];

export const startingPantryIngredients = [
  "eggs",
  "milk",
  "butter",
  "rice",
  "cheese",
];

export const dietaryOptions = [
  { label: "Vegan", tag: "vegan" },
  { label: "Vegetarian", tag: "vegetarian" },
  { label: "Halal", tag: "halal" },
  { label: "Nut allergy", tag: "nut-allergy" },
] satisfies { label: string; tag: DietaryTag }[];
